### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by tsune-sg** [tsune-sg/furima-30491#10]
フリマアプリのURL
https://furima-30491.herokuapp.com/

Basic認証のIDとパスワード
admin     2222

出品者用のメールアドレスとパスワード
aaa@aaa.com
aaa111
購入者用のメールアドレスとパスワード
bbb@bbb.com
aaa111
購入用カードの番号・期限・セキュリティコード
4242424242424242・3/24・123

**Comment by sho0127** [comment]
tsune-sgさん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
[ユーザー新規登録にてパスワードが英語のみでも登録ができてしまいました]
登録した際のパスワードはssssssです！
英数氏混合で6文字以上のパスワードでないと登録ができないように修正しましょう！
修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by tnk1215** [comment]
ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
